// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUKccv-OM8IyHfIhFd4JTzQEGdSUVHopM',
    appId: '1:688336723278:web:5ff433e179bedaa9d0921f',
    messagingSenderId: '688336723278',
    projectId: 'chatapp-fc0ec',
    authDomain: 'chatapp-fc0ec.firebaseapp.com',
    storageBucket: 'chatapp-fc0ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfmaAgmcuLr1a7TaDeIZQG4jqdKmaVOmQ',
    appId: '1:688336723278:android:c6d8d85ebcb5a8ecd0921f',
    messagingSenderId: '688336723278',
    projectId: 'chatapp-fc0ec',
    storageBucket: 'chatapp-fc0ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfbtEbnSo0EJ5tviuIM7Ubagt1mbRYuHk',
    appId: '1:688336723278:ios:510d24e00fc585cdd0921f',
    messagingSenderId: '688336723278',
    projectId: 'chatapp-fc0ec',
    storageBucket: 'chatapp-fc0ec.firebasestorage.app',
    iosBundleId: 'com.example.greenChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfbtEbnSo0EJ5tviuIM7Ubagt1mbRYuHk',
    appId: '1:688336723278:ios:510d24e00fc585cdd0921f',
    messagingSenderId: '688336723278',
    projectId: 'chatapp-fc0ec',
    storageBucket: 'chatapp-fc0ec.firebasestorage.app',
    iosBundleId: 'com.example.greenChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUKccv-OM8IyHfIhFd4JTzQEGdSUVHopM',
    appId: '1:688336723278:web:36a8330824633756d0921f',
    messagingSenderId: '688336723278',
    projectId: 'chatapp-fc0ec',
    authDomain: 'chatapp-fc0ec.firebaseapp.com',
    storageBucket: 'chatapp-fc0ec.firebasestorage.app',
  );
}
